//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Controls : global::System.Configuration.ApplicationSettingsBase {
        
        private static Controls defaultInstance = ((Controls)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Controls())));
        
        public static Controls Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyUp {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyUp"]));
            }
            set {
                this["KeyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyDown {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyDown"]));
            }
            set {
                this["KeyDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyLeft {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyLeft"]));
            }
            set {
                this["KeyLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyRight {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyRight"]));
            }
            set {
                this["KeyRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyFire {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyFire"]));
            }
            set {
                this["KeyFire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyWepForward {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyWepForward"]));
            }
            set {
                this["KeyWepForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyWepBackward {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyWepBackward"]));
            }
            set {
                this["KeyWepBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public global::Microsoft.Xna.Framework.Input.Keys KeyEsc {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["KeyEsc"]));
            }
            set {
                this["KeyEsc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float EffectNoise {
            get {
                return ((float)(this["EffectNoise"]));
            }
            set {
                this["EffectNoise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.18")]
        public float BackgroundMusic {
            get {
                return ((float)(this["BackgroundMusic"]));
            }
            set {
                this["BackgroundMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Difficulty {
            get {
                return ((int)(this["Difficulty"]));
            }
            set {
                this["Difficulty"] = value;
            }
        }
    }
}
